//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Nacion.WebUI.NacionService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetSiguienteCuotaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSiguienteVencimientoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTotalPagadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCantidadCuotasPagasOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCantidadCuotasAdelantadasOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRestoPagarOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVencimientoOriginalOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVencimientoActualOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCuotasOperationCompleted;
        
        private System.Threading.SendOrPostCallback SimularOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInfoGeneralOperationCompleted;
        
        private System.Threading.SendOrPostCallback PagarCuotaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AdelantarCuotaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResetearCuotaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::Nacion.WebUI.Properties.Settings.Default.Nacion_WebUI_NacionService_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetSiguienteCuotaCompletedEventHandler GetSiguienteCuotaCompleted;
        
        /// <remarks/>
        public event GetSiguienteVencimientoCompletedEventHandler GetSiguienteVencimientoCompleted;
        
        /// <remarks/>
        public event GetTotalPagadoCompletedEventHandler GetTotalPagadoCompleted;
        
        /// <remarks/>
        public event GetCantidadCuotasPagasCompletedEventHandler GetCantidadCuotasPagasCompleted;
        
        /// <remarks/>
        public event GetCantidadCuotasAdelantadasCompletedEventHandler GetCantidadCuotasAdelantadasCompleted;
        
        /// <remarks/>
        public event GetRestoPagarCompletedEventHandler GetRestoPagarCompleted;
        
        /// <remarks/>
        public event GetVencimientoOriginalCompletedEventHandler GetVencimientoOriginalCompleted;
        
        /// <remarks/>
        public event GetVencimientoActualCompletedEventHandler GetVencimientoActualCompleted;
        
        /// <remarks/>
        public event GetCuotasCompletedEventHandler GetCuotasCompleted;
        
        /// <remarks/>
        public event SimularCompletedEventHandler SimularCompleted;
        
        /// <remarks/>
        public event GetInfoGeneralCompletedEventHandler GetInfoGeneralCompleted;
        
        /// <remarks/>
        public event PagarCuotaCompletedEventHandler PagarCuotaCompleted;
        
        /// <remarks/>
        public event AdelantarCuotaCompletedEventHandler AdelantarCuotaCompleted;
        
        /// <remarks/>
        public event ResetearCuotaCompletedEventHandler ResetearCuotaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSiguienteCuota", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cuota GetSiguienteCuota() {
            object[] results = this.Invoke("GetSiguienteCuota", new object[0]);
            return ((Cuota)(results[0]));
        }
        
        /// <remarks/>
        public void GetSiguienteCuotaAsync() {
            this.GetSiguienteCuotaAsync(null);
        }
        
        /// <remarks/>
        public void GetSiguienteCuotaAsync(object userState) {
            if ((this.GetSiguienteCuotaOperationCompleted == null)) {
                this.GetSiguienteCuotaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSiguienteCuotaOperationCompleted);
            }
            this.InvokeAsync("GetSiguienteCuota", new object[0], this.GetSiguienteCuotaOperationCompleted, userState);
        }
        
        private void OnGetSiguienteCuotaOperationCompleted(object arg) {
            if ((this.GetSiguienteCuotaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSiguienteCuotaCompleted(this, new GetSiguienteCuotaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSiguienteVencimiento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSiguienteVencimiento() {
            object[] results = this.Invoke("GetSiguienteVencimiento", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSiguienteVencimientoAsync() {
            this.GetSiguienteVencimientoAsync(null);
        }
        
        /// <remarks/>
        public void GetSiguienteVencimientoAsync(object userState) {
            if ((this.GetSiguienteVencimientoOperationCompleted == null)) {
                this.GetSiguienteVencimientoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSiguienteVencimientoOperationCompleted);
            }
            this.InvokeAsync("GetSiguienteVencimiento", new object[0], this.GetSiguienteVencimientoOperationCompleted, userState);
        }
        
        private void OnGetSiguienteVencimientoOperationCompleted(object arg) {
            if ((this.GetSiguienteVencimientoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSiguienteVencimientoCompleted(this, new GetSiguienteVencimientoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTotalPagado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTotalPagado() {
            object[] results = this.Invoke("GetTotalPagado", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTotalPagadoAsync() {
            this.GetTotalPagadoAsync(null);
        }
        
        /// <remarks/>
        public void GetTotalPagadoAsync(object userState) {
            if ((this.GetTotalPagadoOperationCompleted == null)) {
                this.GetTotalPagadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTotalPagadoOperationCompleted);
            }
            this.InvokeAsync("GetTotalPagado", new object[0], this.GetTotalPagadoOperationCompleted, userState);
        }
        
        private void OnGetTotalPagadoOperationCompleted(object arg) {
            if ((this.GetTotalPagadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTotalPagadoCompleted(this, new GetTotalPagadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCantidadCuotasPagas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCantidadCuotasPagas() {
            object[] results = this.Invoke("GetCantidadCuotasPagas", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCantidadCuotasPagasAsync() {
            this.GetCantidadCuotasPagasAsync(null);
        }
        
        /// <remarks/>
        public void GetCantidadCuotasPagasAsync(object userState) {
            if ((this.GetCantidadCuotasPagasOperationCompleted == null)) {
                this.GetCantidadCuotasPagasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCantidadCuotasPagasOperationCompleted);
            }
            this.InvokeAsync("GetCantidadCuotasPagas", new object[0], this.GetCantidadCuotasPagasOperationCompleted, userState);
        }
        
        private void OnGetCantidadCuotasPagasOperationCompleted(object arg) {
            if ((this.GetCantidadCuotasPagasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCantidadCuotasPagasCompleted(this, new GetCantidadCuotasPagasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCantidadCuotasAdelantadas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCantidadCuotasAdelantadas() {
            object[] results = this.Invoke("GetCantidadCuotasAdelantadas", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCantidadCuotasAdelantadasAsync() {
            this.GetCantidadCuotasAdelantadasAsync(null);
        }
        
        /// <remarks/>
        public void GetCantidadCuotasAdelantadasAsync(object userState) {
            if ((this.GetCantidadCuotasAdelantadasOperationCompleted == null)) {
                this.GetCantidadCuotasAdelantadasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCantidadCuotasAdelantadasOperationCompleted);
            }
            this.InvokeAsync("GetCantidadCuotasAdelantadas", new object[0], this.GetCantidadCuotasAdelantadasOperationCompleted, userState);
        }
        
        private void OnGetCantidadCuotasAdelantadasOperationCompleted(object arg) {
            if ((this.GetCantidadCuotasAdelantadasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCantidadCuotasAdelantadasCompleted(this, new GetCantidadCuotasAdelantadasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRestoPagar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRestoPagar() {
            object[] results = this.Invoke("GetRestoPagar", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRestoPagarAsync() {
            this.GetRestoPagarAsync(null);
        }
        
        /// <remarks/>
        public void GetRestoPagarAsync(object userState) {
            if ((this.GetRestoPagarOperationCompleted == null)) {
                this.GetRestoPagarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRestoPagarOperationCompleted);
            }
            this.InvokeAsync("GetRestoPagar", new object[0], this.GetRestoPagarOperationCompleted, userState);
        }
        
        private void OnGetRestoPagarOperationCompleted(object arg) {
            if ((this.GetRestoPagarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRestoPagarCompleted(this, new GetRestoPagarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetVencimientoOriginal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetVencimientoOriginal() {
            object[] results = this.Invoke("GetVencimientoOriginal", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetVencimientoOriginalAsync() {
            this.GetVencimientoOriginalAsync(null);
        }
        
        /// <remarks/>
        public void GetVencimientoOriginalAsync(object userState) {
            if ((this.GetVencimientoOriginalOperationCompleted == null)) {
                this.GetVencimientoOriginalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVencimientoOriginalOperationCompleted);
            }
            this.InvokeAsync("GetVencimientoOriginal", new object[0], this.GetVencimientoOriginalOperationCompleted, userState);
        }
        
        private void OnGetVencimientoOriginalOperationCompleted(object arg) {
            if ((this.GetVencimientoOriginalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVencimientoOriginalCompleted(this, new GetVencimientoOriginalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetVencimientoActual", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetVencimientoActual() {
            object[] results = this.Invoke("GetVencimientoActual", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetVencimientoActualAsync() {
            this.GetVencimientoActualAsync(null);
        }
        
        /// <remarks/>
        public void GetVencimientoActualAsync(object userState) {
            if ((this.GetVencimientoActualOperationCompleted == null)) {
                this.GetVencimientoActualOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVencimientoActualOperationCompleted);
            }
            this.InvokeAsync("GetVencimientoActual", new object[0], this.GetVencimientoActualOperationCompleted, userState);
        }
        
        private void OnGetVencimientoActualOperationCompleted(object arg) {
            if ((this.GetVencimientoActualCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVencimientoActualCompleted(this, new GetVencimientoActualCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCuotas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetCuotas() {
            object[] results = this.Invoke("GetCuotas", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetCuotasAsync() {
            this.GetCuotasAsync(null);
        }
        
        /// <remarks/>
        public void GetCuotasAsync(object userState) {
            if ((this.GetCuotasOperationCompleted == null)) {
                this.GetCuotasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCuotasOperationCompleted);
            }
            this.InvokeAsync("GetCuotas", new object[0], this.GetCuotasOperationCompleted, userState);
        }
        
        private void OnGetCuotasOperationCompleted(object arg) {
            if ((this.GetCuotasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCuotasCompleted(this, new GetCuotasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Simular", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoSimulacion Simular(decimal dinero) {
            object[] results = this.Invoke("Simular", new object[] {
                        dinero});
            return ((ResultadoSimulacion)(results[0]));
        }
        
        /// <remarks/>
        public void SimularAsync(decimal dinero) {
            this.SimularAsync(dinero, null);
        }
        
        /// <remarks/>
        public void SimularAsync(decimal dinero, object userState) {
            if ((this.SimularOperationCompleted == null)) {
                this.SimularOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSimularOperationCompleted);
            }
            this.InvokeAsync("Simular", new object[] {
                        dinero}, this.SimularOperationCompleted, userState);
        }
        
        private void OnSimularOperationCompleted(object arg) {
            if ((this.SimularCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SimularCompleted(this, new SimularCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInfoGeneral", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InfoGeneral GetInfoGeneral() {
            object[] results = this.Invoke("GetInfoGeneral", new object[0]);
            return ((InfoGeneral)(results[0]));
        }
        
        /// <remarks/>
        public void GetInfoGeneralAsync() {
            this.GetInfoGeneralAsync(null);
        }
        
        /// <remarks/>
        public void GetInfoGeneralAsync(object userState) {
            if ((this.GetInfoGeneralOperationCompleted == null)) {
                this.GetInfoGeneralOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInfoGeneralOperationCompleted);
            }
            this.InvokeAsync("GetInfoGeneral", new object[0], this.GetInfoGeneralOperationCompleted, userState);
        }
        
        private void OnGetInfoGeneralOperationCompleted(object arg) {
            if ((this.GetInfoGeneralCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInfoGeneralCompleted(this, new GetInfoGeneralCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PagarCuota", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PagarCuota(int nro) {
            this.Invoke("PagarCuota", new object[] {
                        nro});
        }
        
        /// <remarks/>
        public void PagarCuotaAsync(int nro) {
            this.PagarCuotaAsync(nro, null);
        }
        
        /// <remarks/>
        public void PagarCuotaAsync(int nro, object userState) {
            if ((this.PagarCuotaOperationCompleted == null)) {
                this.PagarCuotaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPagarCuotaOperationCompleted);
            }
            this.InvokeAsync("PagarCuota", new object[] {
                        nro}, this.PagarCuotaOperationCompleted, userState);
        }
        
        private void OnPagarCuotaOperationCompleted(object arg) {
            if ((this.PagarCuotaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PagarCuotaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AdelantarCuota", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AdelantarCuota(int nro) {
            this.Invoke("AdelantarCuota", new object[] {
                        nro});
        }
        
        /// <remarks/>
        public void AdelantarCuotaAsync(int nro) {
            this.AdelantarCuotaAsync(nro, null);
        }
        
        /// <remarks/>
        public void AdelantarCuotaAsync(int nro, object userState) {
            if ((this.AdelantarCuotaOperationCompleted == null)) {
                this.AdelantarCuotaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdelantarCuotaOperationCompleted);
            }
            this.InvokeAsync("AdelantarCuota", new object[] {
                        nro}, this.AdelantarCuotaOperationCompleted, userState);
        }
        
        private void OnAdelantarCuotaOperationCompleted(object arg) {
            if ((this.AdelantarCuotaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdelantarCuotaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ResetearCuota", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ResetearCuota(int nro) {
            this.Invoke("ResetearCuota", new object[] {
                        nro});
        }
        
        /// <remarks/>
        public void ResetearCuotaAsync(int nro) {
            this.ResetearCuotaAsync(nro, null);
        }
        
        /// <remarks/>
        public void ResetearCuotaAsync(int nro, object userState) {
            if ((this.ResetearCuotaOperationCompleted == null)) {
                this.ResetearCuotaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResetearCuotaOperationCompleted);
            }
            this.InvokeAsync("ResetearCuota", new object[] {
                        nro}, this.ResetearCuotaOperationCompleted, userState);
        }
        
        private void OnResetearCuotaOperationCompleted(object arg) {
            if ((this.ResetearCuotaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResetearCuotaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cuota {
        
        private int nroField;
        
        private System.DateTime vencimientoField;
        
        private decimal capitalField;
        
        private decimal interesField;
        
        private decimal cargosField;
        
        private decimal impuestosField;
        
        private StatusCuota statusField;
        
        /// <remarks/>
        public int Nro {
            get {
                return this.nroField;
            }
            set {
                this.nroField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Vencimiento {
            get {
                return this.vencimientoField;
            }
            set {
                this.vencimientoField = value;
            }
        }
        
        /// <remarks/>
        public decimal Capital {
            get {
                return this.capitalField;
            }
            set {
                this.capitalField = value;
            }
        }
        
        /// <remarks/>
        public decimal Interes {
            get {
                return this.interesField;
            }
            set {
                this.interesField = value;
            }
        }
        
        /// <remarks/>
        public decimal Cargos {
            get {
                return this.cargosField;
            }
            set {
                this.cargosField = value;
            }
        }
        
        /// <remarks/>
        public decimal Impuestos {
            get {
                return this.impuestosField;
            }
            set {
                this.impuestosField = value;
            }
        }
        
        /// <remarks/>
        public StatusCuota Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum StatusCuota {
        
        /// <remarks/>
        Nueva,
        
        /// <remarks/>
        Pagada,
        
        /// <remarks/>
        Adelantada,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InfoGeneral {
        
        private string nroClienteField;
        
        private string nroPrestamoField;
        
        private decimal tasaTEMField;
        
        private decimal tasaTNAVField;
        
        private System.DateTime primerVencimientoField;
        
        private System.DateTime ultimoVencimientoField;
        
        private decimal capitalField;
        
        private string cBUField;
        
        private string nroCajaAhorroField;
        
        /// <remarks/>
        public string NroCliente {
            get {
                return this.nroClienteField;
            }
            set {
                this.nroClienteField = value;
            }
        }
        
        /// <remarks/>
        public string NroPrestamo {
            get {
                return this.nroPrestamoField;
            }
            set {
                this.nroPrestamoField = value;
            }
        }
        
        /// <remarks/>
        public decimal TasaTEM {
            get {
                return this.tasaTEMField;
            }
            set {
                this.tasaTEMField = value;
            }
        }
        
        /// <remarks/>
        public decimal TasaTNAV {
            get {
                return this.tasaTNAVField;
            }
            set {
                this.tasaTNAVField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PrimerVencimiento {
            get {
                return this.primerVencimientoField;
            }
            set {
                this.primerVencimientoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime UltimoVencimiento {
            get {
                return this.ultimoVencimientoField;
            }
            set {
                this.ultimoVencimientoField = value;
            }
        }
        
        /// <remarks/>
        public decimal Capital {
            get {
                return this.capitalField;
            }
            set {
                this.capitalField = value;
            }
        }
        
        /// <remarks/>
        public string CBU {
            get {
                return this.cBUField;
            }
            set {
                this.cBUField = value;
            }
        }
        
        /// <remarks/>
        public string NroCajaAhorro {
            get {
                return this.nroCajaAhorroField;
            }
            set {
                this.nroCajaAhorroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultadoSimulacion {
        
        private string nroCuotasAdelantadasField;
        
        private string capitalAdelantadoField;
        
        private string interesesAdelantadosField;
        
        private string vencimientoActualField;
        
        private string nroSiguienteCuotaField;
        
        private string dineroRestanteField;
        
        /// <remarks/>
        public string NroCuotasAdelantadas {
            get {
                return this.nroCuotasAdelantadasField;
            }
            set {
                this.nroCuotasAdelantadasField = value;
            }
        }
        
        /// <remarks/>
        public string CapitalAdelantado {
            get {
                return this.capitalAdelantadoField;
            }
            set {
                this.capitalAdelantadoField = value;
            }
        }
        
        /// <remarks/>
        public string InteresesAdelantados {
            get {
                return this.interesesAdelantadosField;
            }
            set {
                this.interesesAdelantadosField = value;
            }
        }
        
        /// <remarks/>
        public string VencimientoActual {
            get {
                return this.vencimientoActualField;
            }
            set {
                this.vencimientoActualField = value;
            }
        }
        
        /// <remarks/>
        public string NroSiguienteCuota {
            get {
                return this.nroSiguienteCuotaField;
            }
            set {
                this.nroSiguienteCuotaField = value;
            }
        }
        
        /// <remarks/>
        public string DineroRestante {
            get {
                return this.dineroRestanteField;
            }
            set {
                this.dineroRestanteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetSiguienteCuotaCompletedEventHandler(object sender, GetSiguienteCuotaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSiguienteCuotaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSiguienteCuotaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cuota Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cuota)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetSiguienteVencimientoCompletedEventHandler(object sender, GetSiguienteVencimientoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSiguienteVencimientoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSiguienteVencimientoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetTotalPagadoCompletedEventHandler(object sender, GetTotalPagadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTotalPagadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTotalPagadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetCantidadCuotasPagasCompletedEventHandler(object sender, GetCantidadCuotasPagasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCantidadCuotasPagasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCantidadCuotasPagasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetCantidadCuotasAdelantadasCompletedEventHandler(object sender, GetCantidadCuotasAdelantadasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCantidadCuotasAdelantadasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCantidadCuotasAdelantadasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetRestoPagarCompletedEventHandler(object sender, GetRestoPagarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRestoPagarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRestoPagarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetVencimientoOriginalCompletedEventHandler(object sender, GetVencimientoOriginalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVencimientoOriginalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVencimientoOriginalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetVencimientoActualCompletedEventHandler(object sender, GetVencimientoActualCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVencimientoActualCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVencimientoActualCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetCuotasCompletedEventHandler(object sender, GetCuotasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCuotasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCuotasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SimularCompletedEventHandler(object sender, SimularCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SimularCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SimularCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoSimulacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoSimulacion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetInfoGeneralCompletedEventHandler(object sender, GetInfoGeneralCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInfoGeneralCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInfoGeneralCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InfoGeneral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InfoGeneral)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void PagarCuotaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AdelantarCuotaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ResetearCuotaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591